### ISSUE TITLE
[Idea] Create an "All Postman Collections" zip of AEP API Collections JSON files

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/experience-platform-postman-samples#19]
@tsilver WDYT about creating a zip file of all the JSON files in, https://github.com/adobe/experience-platform-postman-samples/tree/master/apis/experience-platform and committing it to Git (in the same folder)?

This would be easy enough to do during the Swagger -> Postman Collection generating process and would provide a single-file download to get the latest set of Postman Collections. 

## Alternatives

Combining the existing Collections for AEP APIs into a single "Uber" postman collection would probably be a difficult/time-consuming and require significant changes to the Swagger -> Postman converter (ie. significant enough where I don't have the time to do them :))

**Comment by tsilver** [comment]
I like easy, so the zip file makes sense.  When I pull all of the collections using git clone, I am able to use the "Load Folder" function in Postman to pull in all of the JSON's in a single collection.  ZIP just means that a single file can be retrieved and extracted to a folder so no git clone is needed, which I am fine with if people don't want to git clone.

**Comment by davidjgonzalez** [comment]
Fixed via #20
